### ISSUE TITLE
Allow to set "isStandardEventVisible"

### ISSUE THREAD

**Issue by berndruecker** [bpmn-io/cmmn-js-properties-panel#41]
The standard allows for this attribute, see page 102:

![issue4](https://cloud.githubusercontent.com/assets/1217596/16082860/48eb6790-3313-11e6-978a-3bd88ff56b3a.png)

It is important as the standard event must be hidden to get business friendly diagrams (at least in e.g. German - as [occur] would confuse readers and is not really necessary here).

![issue3](https://cloud.githubusercontent.com/assets/1217596/16082916/6af9c89a-3313-11e6-8418-0390899d68b3.png)

**Comment by romansmirnov** [comment]
see #40
