### ISSUE TITLE
Keyboard shortcuts problem

### ISSUE THREAD

**Issue by romero83** [bpmn-io/cmmn-js-properties-panel#59]
When typing 'keyboard shortcut key' (like 'h', 'l' etc...) into any property panel field in CMMN then it activates hand tool, lasso tool instead writing of 'h' or 'l' characters.

**Comment by romansmirnov** [comment]
Hi @romero83,

Unfortunately, I am not able to reproduce it in the camunda modeler.

Do you use the camunda modeler? If yes, which version?

Cheers,
Roman
